[package]
name = "rust_spotify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rspotify = "0.12.0"
tokio = {version = "1.35.1", features = ["full"] }